---

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install latest version of "openjdk-21-jdk" ignoring "install-recommends"
  ansible.builtin.apt:
    name: openjdk-21-jdk
    state: latest
    install_recommends: no

- name: Check java version
  ansible.builtin.shell:
    cmd: java -version 2>&1 | grep OpenJDK
  register: java_version
  changed_when: false

- name: Display Open JDK version
  ansible.builtin.debug: 
    var: java_version.stdout

- name: Install Apache Maven
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
        - maven

- name: Check Apache Maven version
  ansible.builtin.shell:
    cmd: mvn -version | grep Apache
  register: mvn_version
  changed_when: false

- name: Display OApache Maven version
  ansible.builtin.debug: 
    var: mvn_version.stdout_lines[0]