---
- name: Update OS
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
      - gnupg2
      - software-properties-common
      - curl
    state: present
    update_cache: yes

- name: Import the Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc 
    state: present

- name: Add the Visual Studio Code repository to your system
  ansible.builtin.apt_repository:
    repo: >- 
      deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    update_cache: yes

# - name: Importe a chave de assinatura GPG 
#   ansible.builtin.shell:
#     cmd: |
#       curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
#       sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
#       cd $HOME

# - name: Adicione o repositório oficial do VS Code
#   ansible.builtin.shell:
#     cmd: |
#       echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | 
#       sudo tee /etc/apt/sources.list.d/vscode.list
#       rm -f packages.microsoft.gpg

- name: Install VScode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: yes

- name: Check VScode version
  ansible.builtin.shell:
    cmd: code -v --user-data-dir --no-sandbox
  register: code_version
  changed_when: false

- name: Display VScode version
  ansible.builtin.debug: 
    var: code_version.stdout